### ISSUE TITLE
Makefile doesn't account for prefix /usr vs. /usr/local

### ISSUE THREAD

**Issue by cwg999** [codebrainz/geany-sidebarterm#1]
Installation prefix

If you want to find Geany's system files after installation you may want to know the installation prefix.

Pass the --print-prefix option to Geany to check this - see Command line options. The first path is the prefix.

On Unix-like systems this is commonly /usr if you installed from a binary package, or /usr/local if you build from source.

**Comment by codebrainz** [comment]
Try `make PREFIX=/some/prefix` or for automatic `make PREFIX=$(pkg-config --variable=prefix geany)` or for only your user just copy the `.so` file to `~/.config/geany/plugins`.
